foody/urls.py
from django.urls import path,include
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.HomePage.as_view(), name="home"),
    path("foody_1/", include("foody_1.urls", namespace="foody_1")),
    path("seller/", include("seller.urls", namespace="seller")),
    path("foody_1/", include("django.contrib.auth.urls")),
    path("test/", views.TestPage.as_view(), name="test"),
    path("thanks/", views.ThanksPage.as_view(), name="thanks"),
    path("about/",views.AboutUS.as_view(),  name='about'),
    path("gallery/",views.GalleryPage.as_view(), name='gallery'),
    path("contact/",views.ContactPage.as_view(),  name='contact'),

]

foody_1/urls.py
from django.urls import path 
from django.contrib.auth import views as auth_views
from . import views

app_name = 'foody_1'
 
urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="foody_1/login.html"),name='login'),
    path("northindian/", views.NorthIndianView.as_view(), name="northindian"),
    path("southindian/", views.SouthIndianView.as_view(), name="southindian"),
    path("italian/", views.ItalianView.as_view(), name="italian"),
    path("chinese/", views.ChineseView.as_view(), name="chinese"),
    path("continental/", views.ContinentalView.as_view(), name="continental"),
    path("fastfood/", views.FastFoodView.as_view(), name="fastfood"),
    path("beverages/", views.beveragesView.as_view(), name="bev"),
    path("deserts/", views.desView.as_view(), name="des"),
    path("confused/", views.ConfusedView.as_view(), name="confused"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("result/", views.resultpage, name="result"),
    path("feedback/", views.feedback, name="feedback"),


    path("confused/happy/", views.HappyView, name="happy"),
    path("confused/angry/", views.AngryView, name="angry"),
    path("confused/dehydrate/", views.DehydrateView, name="dehydrate"),
    path("confused/depress/", views.DepressiveView, name="depress"),
    path("confused/excite/", views.ExciteView, name="excite"),
    path("confused/unwell/", views.UnwellView, name="unwell"),


    path("chinese/noodles/", views.ChineseNoodlesView, name="noodles"),
    path("chinese/chillyPaneer/", views.ChineseChillyPaneerView, name="chillyPaneer"),


    path("continental/ham/", views.ContinentalHamView, name="ham"),
    path("continental/springroll/", views.ContinentalSpringRollView, name="springroll"),



    path("northindian/chollebature/", views.NorthIndianCholleView, name="cholle"),
    path("northindian/rajmachawal/", views.NorthIndianRajmaView, name="rajma"),


    path("southindian/dosa/", views.SouthIndianDosaView, name="dosa"),
    path("southindian/idli/", views.SouthIndianIdliView, name="idli"),


    path("italian/garlicbread/", views.ItalianGarlicView, name="garlic"),
    path("italian/pasta/", views.ItalianPastaView, name="pasta"),



    path("fastfood/aalootikki/", views.FastFoodAalooView, name="aalootikki"),
    path("fastfood/vadapao/", views.FastFoodPaoView, name="vadapao"),


    path("deserts/icecream/", views.IcecreamView, name="icecream"),
    path("deserts/pastries/", views.PastriesView, name="pastries"),
    path("deserts/chocolates/", views.ChocolatesView, name="chocolates"),

    path("beverages/tea/", views.TeaView, name="tea"),
    path("beverages/softdrinks/", views.softdrinksView, name="softdrinks"),
    path("beverages/juices/", views.juicesView, name="juices"),

    ]

seller/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'seller'

urlpatterns=[
    path("seller_form/", views.seller_form.as_view(), name="seller_form"),
]
 

templates/About.html
{% extends 'base.html' %} {% block content %}

<main id="main">
  <!-- ======= About Section ======= -->
  <section id="about" class="about">
    <div class="container" data-aos="fade-up">
      <div class="section-header">
        <h2>About Us</h2>
        <p>Learn More <span>About Us</span></p>
      </div>

      <div class="row gy-4">
        <div
          class="col-lg-7 position-relative about-img"
          style="background-image: url(/static/img/about.jpg)"
          data-aos="fade-up"
          data-aos-delay="150"
        >
          <div class="call-us position-absolute">
            <h4>Book a Table</h4>
            <p>+91 95589 55488</p>
          </div>
        </div>
        <div
          class="col-lg-5 d-flex align-items-end"
          data-aos="fade-up"
          data-aos-delay="300"
        >
          <div class="content ps-0 ps-lg-5">
            <p class="fst-italic">
              One means of doing that is to hold an event in which you invite the public
              to come and sample different items on your menu and offer giveaways.
            </p>
            <ul>
              <li>
                <i class="bi bi-check2-all"></i> Provide an Outstanding Patron Experience.
              </li>
              <li>
                <i class="bi bi-check2-all"></i> Establish Customer Loyalty.
              </li>
              <li>
                <i class="bi bi-check2-all"></i> Offer a Diverse Menu
              </li>
            </ul>
            <p>
              Branding is all about selling the “why” of your restaurant rather
              than the “what,” because patrons already know you offer food.
              The key is to identify what makes your place unique and worth a visit
              Then you must find ways to grab your audience’s attention. 
            </p>

            <div class="position-relative mt-4">
              <img src="/static/img/about-2.jpg" class="img-fluid" alt="" />
              <a
                href="https://www.youtube.com/watch?v=LXb3EKWsInQ"
                class="glightbox play-btn"
              ></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End About Section -->

  <!-- ======= Why Us Section ======= -->
  <section id="why-us" class="why-us section-bg">
    <div class="container" data-aos="fade-up">
      <div class="row gy-4">
        <div class="col-lg-4" data-aos="fade-up" data-aos-delay="100">
          <div class="why-box">
            <h3>Why Choose Foody?</h3>
            <p>
              As time is limited in the Food Service Industry, 
              our main priority is to be a competent point of contact for our customers. 
              Our team understands the importance of bringing you quick and efficient 
              solutions to ease your everyday operations. We take special care in proposing
              only products that fit your needs and assist you in a timely manner.
            </p>
            <div class="text-center">
              <a href="#" class="more-btn"
                >Learn More <i class="bx bx-chevron-right"></i
              ></a>
            </div>
          </div>
        </div>
        <!-- End Why Box -->

        <div class="col-lg-8 d-flex align-items-center">
          <div class="row gy-4">
            <div class="col-xl-4" data-aos="fade-up" data-aos-delay="200">
              <div
                class="icon-box d-flex flex-column justify-content-center align-items-center"
              >
                <i class="bi bi-clipboard-data"></i>
                <h4>New Updates</h4>
                <p>
                 new menu items will be added 
                </p>
              </div>
            </div>
            <!-- End Icon Box -->

            <div class="col-xl-4" data-aos="fade-up" data-aos-delay="300">
              <div
                class="icon-box d-flex flex-column justify-content-center align-items-center"
              >
                <i class="bi bi-gem"></i>
                <h4>Our Milestones</h4>
                <p>
                  James Beard Awards.<br/>
                  Bib Gourmand Awards.<br/>
                  Zagat Awards.<br/>
                </p>
              </div>
            </div>
            <!-- End Icon Box -->

            <div class="col-xl-4" data-aos="fade-up" data-aos-delay="400">
              <div
                class="icon-box d-flex flex-column justify-content-center align-items-center"
              >
                <i class="bi bi-inboxes"></i>
                <h4>Love In Inbox</h4>
                <p>
                  Kai,
                  Eliana,
                  Jayden,
                  Ezra,
                  Luca,
                  Rowan,
                  Nova,
                  Amara,
                  & many others 
                </p>
              </div>
            </div>
            <!-- End Icon Box -->
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Why Us Section -->

  <!-- ======= Stats Counter Section ======= -->
  <section id="stats-counter" class="stats-counter">
    <div class="container" data-aos="zoom-out">
      <div class="row gy-4">
        <div class="col-lg-3 col-md-6">
          <div class="stats-item text-center w-100 h-100">
            <span
              data-purecounter-start="0"
              data-purecounter-end="232"
              data-purecounter-duration="1"
              class="purecounter"
            ></span>
            <p>Clients</p>
          </div>
        </div>
        <!-- End Stats Item -->

        <div class="col-lg-3 col-md-6">
          <div class="stats-item text-center w-100 h-100">
            <span
              data-purecounter-start="0"
              data-purecounter-end="521"
              data-purecounter-duration="1"
              class="purecounter"
            ></span>
            <p>Projects</p>
          </div>
        </div>
        <!-- End Stats Item -->

        <div class="col-lg-3 col-md-6">
          <div class="stats-item text-center w-100 h-100">
            <span
              data-purecounter-start="0"
              data-purecounter-end="1453"
              data-purecounter-duration="1"
              class="purecounter"
            ></span>
            <p>Hours Of Support</p>
          </div>
        </div>
        <!-- End Stats Item -->

        <div class="col-lg-3 col-md-6">
          <div class="stats-item text-center w-100 h-100">
            <span
              data-purecounter-start="0"
              data-purecounter-end="32"
              data-purecounter-duration="1"
              class="purecounter"
            ></span>
            <p>Workers</p>
          </div>
        </div>
        <!-- End Stats Item -->
      </div>
    </div>
  </section>
  <!-- End Stats Counter Section -->
</main>
<!-- End #main -->
{% endblock %}

templates/Contact.html
{% extends 'base.html' %} {% block content %}
<main id="main">
  <!-- ======= Contact Section ======= -->
  <section id="contact" class="contact">
    <div class="container" data-aos="fade-up" style="padding-bottom: 50px;">
      <div class="section-header">
        <h2>Contact</h2>
        <p>Need Help? <span>Contact Us</span></p>
      </div>

      <div class="mb-3">
        <iframe
          style="border: 0; width: 100%; height: 350px"
          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3458.063112338563!2d75.61236659680003!3d20.969473278245438!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bd90f6ed281b505%3A0xab3544dab93ba16a!2sAmar%20Ragda%20MJ%20College%20branch!5e0!3m2!1sen!2sin!4v1680274038122!5m2!1sen!2sin"
          frameborder="0"
          allowfullscreen
        ></iframe>
      </div>
      <!-- End Google Maps -->
      <div class="row gy-4">
        <div class="col-md-6">
          <div class="info-item d-flex align-items-center">
            <i class="icon bi bi-map flex-shrink-0"></i>
            <div>
              <h3>Our Address</h3>
              <p>C/4, Near Ajanta Cinema.
                Khau Galli, Jalgoan-425001</p>
            </div>
          </div>
        </div>
        <!-- End Info Item -->

        <div class="col-md-6">
          <div class="info-item d-flex align-items-center">
            <i class="icon bi bi-envelope flex-shrink-0"></i>
            <div>
              <h3>Email Us</h3>
              <p>foodbymood@demo.com</p>
            </div>
          </div>
        </div>
        <!-- End Info Item -->

        <div class="col-md-6">
          <div class="info-item d-flex align-items-center">
            <i class="icon bi bi-telephone flex-shrink-0"></i>
            <div>
              <h3>Call Us</h3>
              <p>+91 95896 75488</p>
            </div>
          </div>
        </div>
        <!-- End Info Item -->

        <div class="col-md-6">
          <div class="info-item d-flex align-items-center">
            <i class="icon bi bi-people flex-shrink-0"></i>
            <div>
              <h3>Developers</h3>
              <div>
                <p><strong>Front-end:</strong> Ms.Aarti Ware</p>
                <p><strong>Back-end:</strong> Mr.Pankaj Shinde</p>
              </div>
            </div>
          </div>
        </div>

        <!-- End Info Item -->
      </div>
      <!--End Contact Form -->
    </div>
  </section>
  <!-- End Contact Section -->
</main>
<!-- End #main -->
{% endblock %}

templates/Gallery.html
{% extends 'base.html' %} {% block content %}
<main id="main">
  <!-- ======= Gallery Section ======= -->
  <section id="gallery" class="gallery section-bg">
    <div class="container-xxl" data-aos="fade-up" style="padding-top: 50px;">
      <div class="section-header">
        <h2>gallery</h2>
        <p>Check <span>Our Gallery</span></p>
      </div>

      <div class="gallery-slider swiper">
        <div class="swiper-wrapper align-items-center">
          <div class="swiper-slide">
            <a
              class="glightbox"
              data-gallery="images-gallery"
              href="/static/img/gallery/gallery-1.jpg"
              ><img
                src="/static/img/gallery/gallery-1.jpg"
                class="img-fluid"
                alt=""
            /></a>
          </div>
          <div class="swiper-slide">
            <a
              class="glightbox"
              data-gallery="images-gallery"
              href="/static/img/gallery/gallery-2.jpg"
              ><img
                src="/static/img/gallery/gallery-2.jpg"
                class="img-fluid"
                alt=""
            /></a>
          </div>
          <div class="swiper-slide">
            <a
              class="glightbox"
              data-gallery="images-gallery"
              href="/static/img/gallery/gallery-3.jpg"
              ><img
                src="/static/img/gallery/gallery-3.jpg"
                class="img-fluid"
                alt=""
            /></a>
          </div>
          <div class="swiper-slide">
            <a
              class="glightbox"
              data-gallery="images-gallery"
              href="/static/img/gallery/gallery-4.jpg"
              ><img
                src="/static/img/gallery/gallery-4.jpg"
                class="img-fluid"
                alt=""
            /></a>
          </div>
          <div class="swiper-slide">
            <a
              class="glightbox"
              data-gallery="images-gallery"
              href="/static/img/gallery/gallery-5.jpg"
              ><img
                src="/static/img/gallery/gallery-5.jpg"
                class="img-fluid"
                alt=""
            /></a>
          </div>
          <div class="swiper-slide">
            <a
              class="glightbox"
              data-gallery="images-gallery"
              href="/static/img/gallery/gallery-6.jpg"
              ><img
                src="/static/img/gallery/gallery-6.jpg"
                class="img-fluid"
                alt=""
            /></a>
          </div>
          <div class="swiper-slide">
            <a
              class="glightbox"
              data-gallery="images-gallery"
              href="/static/img/gallery/gallery-7.jpg"
              ><img
                src="/static/img/gallery/gallery-7.jpg"
                class="img-fluid"
                alt=""
            /></a>
          </div>
          <div class="swiper-slide">
            <a
              class="glightbox"
              data-gallery="images-gallery"
              href="/static/img/gallery/gallery-8.jpg"
              ><img
                src="/static/img/gallery/gallery-8.jpg"
                class="img-fluid"
                alt=""
            /></a>
          </div>
        </div>
        <div class="swiper-pagination">
          pa nka
        </div>
      </div>
    </div>
  </section>
  <!-- End Gallery Section -->

  <!-- ======= Events Section ======= -->
  <section id="events" class="events">
    <div class="p-5 container-md" data-aos="fade-up">
      <div class="section-header">
        <h2>Events</h2>
        <p>Share <span>Your Moments</span> In Our Restaurant</p>
      </div>

      <div class="slides-3 swiper" data-aos="fade-up" data-aos-delay="100">
        <div class="swiper-wrapper">
          <div
            class="swiper-slide event-item d-flex flex-column justify-content-end"
            style="background-image: url(/static/img/events-1.jpg)"
          >
            <h3>Custom Parties</h3>
            <div class="price align-self-start">Join Us</div>
            <p class="description">
              At Party City, we've got the largest selection of personalized party supplies,<br/>
              including: Custom Banners. Holiday Photo Cards.
            </p>
          </div>
          <!-- End Event item -->

          <div
            class="swiper-slide event-item d-flex flex-column justify-content-end"
            style="background-image: url(/static/img/events-2.jpg)"
          >
            <h3>Private Parties</h3>
            <div class="price align-self-start">Join Us</div>
            <p class="description">
              legant and Comfortable Accommodations<br/>
              • Meals “Prepared to Order” by Our Skilled Chefs.<br/>
              • Top Shelf Spirits and Premium American Wines.
            </p>
          </div>
          <!-- End Event item -->

          <div
            class="swiper-slide event-item d-flex flex-column justify-content-end"
            style="background-image: url(/static/img/events-3.jpg)"
          >
            <h3>Birthday Parties</h3>
            <div class="price align-self-start">Join Us</div>
            <p class="description">
              Celebrate your birthday, kids party with us <br/>
              • Cake “Prepared to Order” by Our Skilled Chefs.<br/>
              • special Dominos pizza deals.
            </p>
          </div>
          <!-- End Event item -->
        </div>
        <div class="swiper-pagination"></div>
      </div>
    </div>
  </section>
  <!-- End Events Section -->
</main>
<!-- End #main -->
{% endblock %}

templates/header.html
<!-- ======= Header ======= -->
<body>
<header id="header" class="header fixed-top d-flex align-items-center ">
  <div class="container d-flex align-items-center justify-content-between"> 
    <a
      href="{% url 'home' %}"
      class="logo d-flex align-items-center me-auto me-lg-0"
    >
      <h1>Food By Mood<span>.</span></h1>
    </a>
            
    <nav id="navbar" class="navbar">
      <ul>
        <li>
          {% if user.is_authenticated %}
          <a class="{% if request.path == '/' %}  nav-link active {% endif %}"
            href="{% url 'home' %}">
              Home
          </a>
        </li>
        <li>
          <a class="{% if request.path == '/test/' %}  nav-link active {% endif %}"
            href="{% url 'test' %}">
              Menu
          </a>
             {% else %}
          <a class="{% if request.path == '/' %}  nav-link active {% endif %}"
            href="{% url 'home' %}">
              Home
          </a>
            {% endif %}
        </li>       
           
        <li>
          <a href="{% url "about" %}" 
            class="{% if request.path == '/about/' %}  nav-link active {% endif %}">
            About
          </a>
        </li>       
        <li>
          <a href="{% url "gallery" %}" 
            class="{% if request.path == '/gallery/' %}  nav-link active {% endif %}">
            Gallery
          </a>
        </li>       
        <li>
          <a href="{% url "contact" %}" 
            class="{% if request.path == '/contact/' %}  nav-link active {% endif %}">
            Contact
          </a>
        </li>
      </ul>
    </nav>
    <!-- .navbar -->
  </div>
  <div>
      {% if user.is_authenticated %} 
        <div style="text-align:center;  padding-bottom:10px;">
          <h4 style="padding:10px;"><i>Welcome! </i><span>{{ user.first_name }} {{ user.last_name }}</span></h4>
          <a href="{% url 'foody_1:logout' %}" class="btn-book-a-table">Log Out</a>
        </div>
      {% else %}
          <div style="margin-right: 50px; padding:10px;">
            <a href="{% url 'foody_1:login' %}" class="btn-book-a-table">Log In</a> 
          </div>
          <div style="margin-right: 50px; padding:10px;">
            <a href="{% url 'foody_1:signup' %}" class="btn-book-a-table">Sign Up</a>
          </div>
      {% endif %}
  </div>
    <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
    <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
</header>
<!-- End Header -->

templates/index.html
{% extends "base.html" %} {% block headblock %}
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css"
/>
<link
  href="https://fonts.googleapis.com/css?family=Poor+Story"
  rel="stylesheet"
/>
{% endblock %} 
{% block fullscreen %}


<!-- ======= Hero Section ======= -->
<section id="hero" class="hero d-flex align-items-center section-bg">
  <div class="container">
    <div class="row justify-content-between gy-5">
      <div
        class="col-lg-7 order-2 order-lg-2 d-flex flex-column justify-content-center align-items-center align-items-lg-start text-center text-lg-start"
      >
        <h2 data-aos="fade-up">Enjoy Your Healthy<br />Delicious Food</h2>
       
        <div class="d-flex" data-aos="fade-up" data-aos-delay="200">
          {% if not user.is_authenticated %}
            <h3>
              Do You Want To Sell Food? <br/><br/>
              <a
                align="center"
                href="{% url 'seller:seller_form' %}"
                class="btn-book-a-table">
                sell on Foody!<br/>
              </a>
            </h3>
          {% else %}
            <h3>
              Feeling Moody ?<br/> Cant Decide What To Eat ?<br/><br/>
              <a 
                align="center"
                href="{% url 'foody_1:confused' %}"
                class="btn-book-a-table">
                We Can Help !<br/>
              </a>
            </h3>
          {% endif %}
        </div>
      </div>
      <div class="col-lg-5 order-1 order-lg-2 text-center text-lg-start">
        <img 
          src="/static/img/hero.png"
          class="img-fluid"
          alt=""
          data-aos="zoom-out"
          data-aos-delay="300"
        />
      </div>
    </div>
  </div>
</section>
<!-- End Hero Section -->

{% endblock %}

templates/test.html
{% extends "base.html" %}
{% load static %}
{% block headblock %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
  
{% endblock %}

{% block fullscreen %}
<main id="main">
<section id="menu" class="menu section-bg">
  <div class="container-md" data-aos="fade-up">
    <div class="section-header " style="padding-top: 20px;"> 
      <h2>Our Cuisines</h2>
      <p>Check Our <span>Available Cuisines</span></p>
    </div>

    <div class="col">
      <div class="col-lg-4 " style="padding-bottom: 25px;">
        <div class="card" style="width: 35rem; ">
          <div class="card-body">
            <a href="{% url 'foody_1:northindian' %}" >
            <h3 class="card-text">North Indian</h3>
            <img src="/static/img/menu/north.jpg"
            class="card-img-top" 
            alt="North Indian">
          </div>
        </div>
      </div>

      <div class="col-lg-4 " style="padding-bottom: 25px;">
        <div class="card" style="width: 35rem; ">
          <div class="card-body">
            <a href="{% url 'foody_1:southindian' %}">
            <h3 class="card-text">South Indian</h3>
            <img  src="/static/img/menu/south.jpg" 
            class="card-img-top" 
            alt="south indian">
          </div>
        </div>
      </div>

      <div class="col-lg-4 " style="padding-bottom: 25px;">
        <div class="card" style="width: 35rem; ">
          <div class="card-body">
            <a href="{% url 'foody_1:italian' %}">
            <h3 class="card-text">Italian</h3>
            <img  src="/static/img/menu/italian.jpg" 
            class="card-img-top" 
            alt="italian">
          </div>
        </div>
      </div>

      <div class="col-lg-4 " style="padding-bottom: 25px;">
        <div class="card" style="width: 35rem; ">
          <div class="card-body">
            <a href="{% url 'foody_1:chinese' %}">
            <h3 class="card-text">Chinese</h3>
            <img  src="/static/img/menu/chinese.jpg" 
            class="card-img-top" 
            alt="chinese">
          </div>
        </div>
      </div>

      <div class=" col-lg-4 " style=" padding-bottom: 25px;">
        <a href="{% url 'foody_1:confused' %}">
        <div class="card" style="width: 35rem; height: 37.2rem;">
          <div class="card-body"  style=" padding-top: 75px;">
            <p class=" f card-text">Hello <span>{{ user.first_name }} {{ user.last_name }} !</span></p>
            <h4 class="card-text">You're successfully logged in.<br/><br/>
            Feeling Moody ? <br/><br/>
            Can't decide ? <br/><br/>
            We can help !</h4>
          </div>
        </div>
      </div>

      <div class="col-lg-4 " style="padding-bottom: 25px;">
        <div class="card" style="width: 35rem; ">
          <div class="card-body">
            <a href="{% url 'foody_1:continental' %}">
            <h3 class="card-text">Continental</h3>
            <img  src="/static/img/menu/continental.jpg" 
            class="card-img-top" 
            alt="continental">
          </div>
        </div>
      </div>
      
      <div class="col-lg-4 " style="padding-bottom: 25px;">
        <div class="card" style="width: 35rem; ">
          <div class="card-body">
            <a href="{% url 'foody_1:fastfood' %}">
            <h3 class="card-text">Fast Food</h3>
            <img  src="/static/img/menu/fastfood.jpg" 
            class="card-img-top" 
            alt="fastfood">
          </div>
        </div>
      </div>

      <div class="col-lg-4 " style="padding-bottom: 25px;">
        <div class="card" style="width: 35rem; ">
          <div class="card-body">
            <a href="{% url 'foody_1:bev' %}">
            <h3 class="card-text">Beverages</h3>
            <img  src="/static/img/menu/beverages.jpg" 
            class="card-img-top" 
            alt="beverages">
          </div>
        </div>
      </div>

      <div class="col-lg-4 " style="padding-bottom: 25px;">
        <div class="card" style="width: 35rem; ">
          <div class="card-body">
            <a href="{% url 'foody_1:des' %}">
            <h3 class="card-text">Dessert</h3>
            <img  src="/static/img/menu/dessert.jpg" 
            class="card-img-top" 
            alt="dessert">
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</main>
<style>
  .card {
    background-color : #131A24;
    border:none;
    text-align: center;
    color: white;
    font-weight : bold ;
    cursor:pointer;
  }
  
  .card :hover {
    background-color: #ffbe33;
    color: #131A24;
    font-weight : bold;
  }
  
  .f {
    font-size : 25px;
  }

</style>
{% endblock %}

templates/thanks.html
{% extends "base.html" %} {% load static %} {% block headblock %}
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css"
/>

<link
  href="https://fonts.googleapis.com/css?family=Poor+Story"
  rel="stylesheet"
/>
{% endblock %} {% block fullscreen %}
<section id="hero" class="hero d-flex align-items-center section-bg gap">
  <div class="container">
    <div class="row justify-content-between gy-5">
      <h2 class="head_mansi">Thank You For visiting</h2>
      <p class="link">Let Your Food Choose You !</p>
      <hr
        style="
          height: 2px;
          border-width: 0;
          color: gray;
          background-color: gray;
        "
      />
    </div>
  </div>
</section>

<style media="screen">
  .link {
    text-align: center;
    font-size: 20px;
    font-family: "Poor Story", cursive;
  }
  .under_tag {
    color: black;
    font-size: 25px;
    font-family: "Poor Story", cursive;
  }
  .head_mansi {
    color: black;
    font-size: 100px;
    text-align: center;
    font-family: "Poor Story", cursive;
  }
</style>
{% endblock %}